### ISSUE TITLE
Too restrictive blacklisting for systemd-resolved, unable to browse the web due to broken resolv.conf symlink

### ISSUE THREAD

**Issue by ThibaultMndr** [netblue30/firejail#1547]
With firejail 0.9.50 on Arch, `disable-common.inc` blacklists `/var/run/systemd`. But with a systemd-resolved configuration `/etc/resolv.conf` is a symlink to `/var/run/systemd/resolve/resolv.conf`, so the link is broken in jails.

Adding `noblacklist /var/run/systemd` before including `/etc/firejail/disable-common.inc` in profiles that require accessing internet is a workaround. 

It should be more secure to only allow access to `/var/run/systemd/resolve/resolv.conf` but I don't know if it is possible without blacklisting individually all `var/run/systemd` subfolders

**Comment by netblue30** [comment]
I'll disable the blacklist in /etc/firejail/disable-common.inc, thanks for the bug.

**Comment by netblue30** [comment]
Fixed: https://github.com/netblue30/firejail/commit/1e879f1199fb3a3647a5eefd7a8f34bbdc8b8098

**Comment by oxwivi** [comment]
Does this issue still apply to the version shipping with Ubuntu 16.04 repo?

**Comment by oxwivi** [comment]
I compiled and installed, yes, issue still applies to the version shipping on Ubuntu repos. However, the `firejail` on repo version added a helpful `[]` indicator around the prompt to show currently in `firejail`'d env, compiled version doesn't. How do I activate it?
