### ISSUE TITLE
[INFO] How exactly does one use --private-lib?

### ISSUE THREAD

**Issue by chiraag-nataraj** [netblue30/firejail#1717]
So I saw the `--private-lib` option and decided to play around with it a bit, but I couldn't actually get it to like me. Using the firefox profile attached, I decided to try `firejail --profile=.config/firejail/firefox.profile --private-lib=firefox sh` and it gave me this output:
````
Reading profile .config/firejail/firefox.profile
Reading profile /etc/firejail/globals.local
Parent pid 21880, child pid 21881
Private /etc installed in 34.58 ms
Standard C library installed in 29.56 ms
Warning fldd: cannot find libmozavutil.so, skipping...
Warning fldd: cannot find libmozsandbox.so, skipping...
Warning fldd: cannot find liblgpllibs.so, skipping...
Warning fldd: cannot find libmozgtk.so, skipping...
Error stat: main.c:286 walk_directory: No such file or directory
Error: failed to run /usr/lib/x86_64-linux-gnu/firejail/fldd
Error: proc 21880 cannot sync with peer: unexpected EOF
Peer 21881 unexpectedly exited with status 1
````
The thing is, those libraries are in `/usr/lib/firefox`, and even including `x86_64-linux-gnu/firejail` in the `--private-lib` path (which...shouldn't it already be included?) didn't help. I know I'm using `--private-lib` wrong, I just don't know why.
TIA!
[firefox.txt](https://github.com/netblue30/firejail/files/1611442/firefox.txt)

**Comment by topimiettinen** [comment]
Please retry with --debug, that should tell a bit more what's happening.

**Comment by chiraag-nataraj** [comment]
I get this after `Standard C library installed in 98.72 ms`:
````
fslib_copy_libs firefox
cannot find firefox for private-lib, skipping...
Copying extra files (firefox) in the new lib directory
fslib_copy_dir /usr/lib/firefox
fslib_copy_libs /usr/lib/firefox
Creating empty /run/firejail/mnt/libfiles file
running fldd /usr/lib/firefox
sbox run: /usr/lib/x86_64-linux-gnu/firejail/fldd /usr/lib/firefox /run/firejail/mnt/libfiles (null) 
sbox file descriptors:
total 0
lrwx------ 1 root 0 64 Jan  8 12:14 0 -> /dev/null
lrwx------ 1 root 0 64 Jan  8 12:14 1 -> /dev/pts/1
lrwx------ 1 root 0 64 Jan  8 12:14 2 -> /dev/pts/1
lr-x------ 1 root 0 64 Jan  8 12:14 3 -> /proc/3934/fd
Dropping all capabilities
Username chiraag, no supplementary groups
Warning fldd: cannot find libmozavutil.so, skipping...
Warning fldd: cannot find libmozsandbox.so, skipping...
Warning fldd: cannot find liblgpllibs.so, skipping...
Warning fldd: cannot find libmozgtk.so, skipping...
Error stat: main.c:286 walk_directory: No such file or directory
Error: failed to run /usr/lib/x86_64-linux-gnu/firejail/fldd
Error: proc 3794 cannot sync with peer: unexpected EOF
Peer 3795 unexpectedly exited with status 1
````

**Comment by chiraag-nataraj** [comment]
Here's the full output from `firejail --private-lib firefox --debug-private-lib firefox`:
````
Reading profile /home/chiraag/.config/firejail/firefox.profile
Reading profile /etc/firejail/globals.local
Parent pid 6748, child pid 6749
Private /etc installed in 29.65 ms
Starting private-lib processing: program firefox, shell none
copying /lib/x86_64-linux-gnu/libm.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libresolv.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libpthread.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libmvec.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libc.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libthread_db.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_compat.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libanl.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_files.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_nis.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/librt.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libcrypt.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libmemusage.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libutil.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_nisplus.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_dns.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_hesiod.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libselinux.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libcidn.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnsl.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libdl.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_dir /usr/lib/locale
Standard C library installed in 30.34 ms
fslib_copy_libs firefox
cannot find firefox for private-lib, skipping...
Copying extra files (firefox) in the new lib directory
fslib_copy_dir /usr/lib/firefox
fslib_copy_libs /usr/lib/firefox
running fldd /usr/lib/firefox
Warning fldd: cannot find libmozavutil.so, skipping...
Warning fldd: cannot find libmozsandbox.so, skipping...
Warning fldd: cannot find liblgpllibs.so, skipping...
Warning fldd: cannot find libmozgtk.so, skipping...
Error stat: main.c:286 walk_directory: No such file or directory
Error: failed to run /usr/lib/x86_64-linux-gnu/firejail/fldd
Error: proc 6748 cannot sync with peer: unexpected EOF
Peer 6749 unexpectedly exited with status 1
````

**Comment by topimiettinen** [comment]
```
fslib_copy_libs firefox
cannot find firefox for private-lib, skipping...
```
This means that "firefox" can't be accessed. Is it in your $PATH? Is /usr/lib/firefox a program, directory or symlink? What's output of
`ls -ld /usr/{bin,lib}/firefox
`
?

**Comment by chiraag-nataraj** [comment]
`/usr/lib/firefox` is the directory containing the libraries necessary for firefox to work. The actual binary is `/usr/bin/firefox`. Both exist as shown by:
````
*chiraag@chiraag@17:50:-100%:~ $ ls -ld /usr/{bin,lib}/firefox
lrwxrwxrwx  1 root root   22 Jan  5 02:19 /usr/bin/firefox -> ../lib/firefox/firefox
drwxr-xr-x. 7 root root 4096 Jan  6 18:37 /usr/lib/firefox
````
If I don't use `private-lib`, everything loads fine, which implies `firefox` is in my path and everything else is dandy (and, indeed, it is).

**Comment by topimiettinen** [comment]
I pushed 4ee58af2 which should fix the issue, please try.

**Comment by chiraag-nataraj** [comment]
I don't know if it matters where I install `firejail`, but I installed it to `/usr/local` and it didn't fix the problem (yes, `firejail` _is_ actually running the one from git, not the distro-installed one - I checked). I will try overwriting the distro-installed version and see if that helps.

**Comment by chiraag-nataraj** [comment]
Still getting the exact same error:
````
Reading profile /home/chiraag/.config/firejail/firefox.profile
Reading profile /etc/firejail/globals.local
Parent pid 8658, child pid 8659
Private /etc installed in 28.84 ms
Starting private-lib processing: program firefox, shell none
copying /lib/x86_64-linux-gnu/libm.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libresolv.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libpthread.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libmvec.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libc.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libthread_db.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_compat.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libanl.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_files.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_nis.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/librt.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libcrypt.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libmemusage.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libutil.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_nisplus.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_dns.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_hesiod.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libselinux.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libcidn.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnsl.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libdl.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_dir /usr/lib/locale
Standard C library installed in 29.15 ms
fslib_copy_libs firefox
cannot find firefox for private-lib, skipping...
Copying extra files (firefox) in the new lib directory
fslib_copy_dir /usr/lib/firefox
fslib_copy_libs /usr/lib/firefox
running fldd /usr/lib/firefox
Warning fldd: cannot find libmozavutil.so, skipping...
Warning fldd: cannot find libmozsandbox.so, skipping...
Warning fldd: cannot find liblgpllibs.so, skipping...
Warning fldd: cannot find libmozgtk.so, skipping...
Error stat: main.c:286 walk_directory: No such file or directory
Error: failed to run /usr/lib/firejail/fldd
Error: proc 8658 cannot sync with peer: unexpected EOF
Peer 8659 unexpectedly exited with status 1
````

**Comment by topimiettinen** [comment]
How about now with 29cab4a046926fbf298922fb7363736924ee8339?

**Comment by chiraag-nataraj** [comment]
We get further this time:
````
*chiraag@chiraag@12:48:-100%:~ $ firejail --private-lib=firefox,x86_64-linux-gnu/libgtk-3.so,x86_64-linux-gnu/libjsoncpp.so.1,x86_64-linux-gnu/libplds4.so,x86_64-linux-gnu/libplc4.so,x86_64-linux-gnu/libssl3.so,x86_64-linux-gnu/libsmime3.so,x86_64-linux-gnu/libhunspell-1.6.so.0,x86_64-linux-gnu/libevent-2.1.so.6,x86_64-linux-gnu/libvpx.so.4,x86_64-linux-gnu/libdbus-glib-1.so.2,x86_64-linux-gnu/libstartup-notification-1.so.0,x86_64-linux-gnu/libXt.so.6 --debug-private-lib firefox --no-remote -P FailSafe
Reading profile /home/chiraag/.config/firejail/firefox.profile
Reading profile /etc/firejail/globals.local
Parent pid 2756, child pid 2757
Private /etc installed in 28.74 ms
Starting private-lib processing: program firefox, shell none
copying /lib/x86_64-linux-gnu/libm.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libresolv.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libpthread.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libmvec.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libc.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libthread_db.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_compat.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libanl.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_files.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_nis.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/librt.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libcrypt.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libmemusage.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libutil.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_nisplus.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_dns.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnss_hesiod.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libselinux.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libcidn.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libnsl.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libdl.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_dir /usr/lib/locale
Standard C library installed in 27.69 ms
fslib_copy_libs firefox
cannot find firefox for private-lib, skipping...
Copying extra files (firefox,x86_64-linux-gnu/libgtk-3.so,x86_64-linux-gnu/libjsoncpp.so.1,x86_64-linux-gnu/libplds4.so,x86_64-linux-gnu/libplc4.so,x86_64-linux-gnu/libssl3.so,x86_64-linux-gnu/libsmime3.so,x86_64-linux-gnu/libhunspell-1.6.so.0,x86_64-linux-gnu/libevent-2.1.so.6,x86_64-linux-gnu/libvpx.so.4,x86_64-linux-gnu/libdbus-glib-1.so.2,x86_64-linux-gnu/libstartup-notification-1.so.0,x86_64-linux-gnu/libXt.so.6) in the new lib directory
fslib_copy_dir /usr/lib/firefox
copying /usr/lib/x86_64-linux-gnu/libgtk-3.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libgtk-3.so
running fldd /usr/lib/x86_64-linux-gnu/libgtk-3.so
copying /usr/lib/x86_64-linux-gnu/libatspi.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/liblz4.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/liblzma.so.5 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libgpg-error.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libgcrypt.so.20 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libsystemd.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libdbus-1.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libepoxy.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXdamage.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXfixes.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXcursor.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXrandr.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXi.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXinerama.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libuuid.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libblkid.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libmount.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXext.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libX11.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXrender.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libbsd.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXau.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libxcb.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libexpat.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libz.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libpng16.so.16 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libfreetype.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libcairo.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libdatrie.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libthai.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libffi.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib64/ld-linux-x86-64.so.2 to private /run/firejail/mnt/lib
copying /lib/x86_64-linux-gnu/libpcre.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libglib-2.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1
running fldd /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1
copying /lib/x86_64-linux-gnu/libgcc_s.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libstdc++.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libplds4.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libplds4.so
running fldd /usr/lib/x86_64-linux-gnu/libplds4.so
copying /usr/lib/x86_64-linux-gnu/libnspr4.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libplc4.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libplc4.so
running fldd /usr/lib/x86_64-linux-gnu/libplc4.so
copying /usr/lib/x86_64-linux-gnu/libssl3.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libssl3.so
running fldd /usr/lib/x86_64-linux-gnu/libssl3.so
copying /usr/lib/x86_64-linux-gnu/libnssutil3.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libnss3.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libsmime3.so to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libsmime3.so
running fldd /usr/lib/x86_64-linux-gnu/libsmime3.so
copying /usr/lib/x86_64-linux-gnu/libhunspell-1.6.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libhunspell-1.6.so.0
running fldd /usr/lib/x86_64-linux-gnu/libhunspell-1.6.so.0
copying /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
running fldd /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
copying /usr/lib/x86_64-linux-gnu/libvpx.so.4 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libvpx.so.4
running fldd /usr/lib/x86_64-linux-gnu/libvpx.so.4
copying /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
running fldd /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
copying /usr/lib/x86_64-linux-gnu/libstartup-notification-1.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libstartup-notification-1.so.0
running fldd /usr/lib/x86_64-linux-gnu/libstartup-notification-1.so.0
copying /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libxcb-util.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libXt.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libXt.so.6
running fldd /usr/lib/x86_64-linux-gnu/libXt.so.6
copying /usr/lib/x86_64-linux-gnu/libICE.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libSM.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_libs /usr/bin/firefox
running fldd /usr/bin/firefox
fslib_copy_dir /usr/lib/firefox
fslib_copy_libs /usr/bin/which
running fldd /usr/bin/which
Warning fldd: /usr/bin/which is not an ELF executable or library
fslib_copy_libs /bin/sh
running fldd /bin/sh
fslib_copy_libs /usr/bin/dbus-launch
running fldd /usr/bin/dbus-launch
fslib_copy_libs /usr/bin/dbus-send
running fldd /usr/bin/dbus-send
fslib_copy_libs /usr/bin/env
running fldd /usr/bin/env
Program libraries installed in 164.70 ms
fslib_copy_libs /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0
running fldd /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0
copying /usr/lib/x86_64-linux-gnu/libjbig.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libtiff.so.5 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libjpeg.so.62 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libicudata.so.57 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libicuuc.so.57 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libicui18n.so.57 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libxml2.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/librsvg-2.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_dir /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0
GdkPixbuf installed in 78.77 ms
fslib_copy_libs /usr/lib/x86_64-linux-gnu/gtk-3.0
running fldd /usr/lib/x86_64-linux-gnu/gtk-3.0
copying /usr/lib/x86_64-linux-gnu/libcanberra-gtk3.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libltdl.so.7 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libtdb.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libogg.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libvorbis.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libcanberra.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libsoup-gnome-2.4.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/librest-0.7.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libavahi-common.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgmp.so.10 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libhogweed.so.4 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libnettle.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libtasn1.so.6 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libunistring.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libidn2.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgnutls.so.30 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libcom_err.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libkeyutils.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libkrb5.so.3 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libcups.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/liblcms2.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libcolordprivate.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /lib/x86_64-linux-gnu/libudev.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libcolord.so.2 to private /run/firejail/mnt/lib/x86_64-linux-gnu
copying /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_dir /usr/lib/x86_64-linux-gnu/gtk-3.0
fslib_copy_libs /usr/lib/x86_64-linux-gnu/libgtk-3-0
running fldd /usr/lib/x86_64-linux-gnu/libgtk-3-0
fslib_copy_dir /usr/lib/x86_64-linux-gnu/libgtk-3-0
GTK3 installed in 81.85 ms
Pango installed in 0.02 ms
fslib_copy_libs /usr/lib/x86_64-linux-gnu/gio
running fldd /usr/lib/x86_64-linux-gnu/gio
copying /usr/lib/x86_64-linux-gnu/libproxy.so.1 to private /run/firejail/mnt/lib/x86_64-linux-gnu
fslib_copy_dir /usr/lib/x86_64-linux-gnu/gio
GIO installed in 3.79 ms
Installed 145 libraries and 6 directories
fslib_copy_dir /usr/local/lib/firejail
fslib_copy_libs /usr/local/lib/firejail/faudit
running fldd /usr/local/lib/firejail/faudit
fslib_copy_libs /usr/local/lib/firejail/fbuilder
running fldd /usr/local/lib/firejail/fbuilder
fslib_copy_libs /usr/local/lib/firejail/fcopy
running fldd /usr/local/lib/firejail/fcopy
fslib_copy_libs /usr/local/lib/firejail/fldd
running fldd /usr/local/lib/firejail/fldd
fslib_copy_libs /usr/local/lib/firejail/fnet
running fldd /usr/local/lib/firejail/fnet
fslib_copy_libs /usr/local/lib/firejail/fnetfilter
running fldd /usr/local/lib/firejail/fnetfilter
fslib_copy_libs /usr/local/lib/firejail/fseccomp
running fldd /usr/local/lib/firejail/fseccomp
fslib_copy_libs /usr/local/lib/firejail/ftee
running fldd /usr/local/lib/firejail/ftee
Mount-bind /run/firejail/mnt/lib on top of /lib /lib64 /usr/lib
Child process initialized in 431.16 ms
````
So firefox starts up just fine. But trying to actually open any pages (other than `about:`-style pages) results in the URL bar losing focus and no site actually loading. Since I don't get any error messages from `--debug-private-lib`, I'm not sure what exactly is going on (it's probably a library problem, but...no error messages).

**Comment by chiraag-nataraj** [comment]
The solution is given in #1920. Closing this.
