### ISSUE TITLE
Firefox 60+ fails to run content processes

### ISSUE THREAD

**Issue by johnp** [netblue30/firejail#1765]
Firefox Nightly doesn't seem to be able to start child processes / no tabs loading websites (except `about:`-stuff, which AFAIK runs in the parent process), crashing them instead:

https://crash-stats.mozilla.com/report/index/288d3c2b-c0be-4a85-af97-b294f0180207

I suspect [bug 1401062](https://bugzilla.mozilla.org/show_bug.cgi?id=1401062) to be the issue, but don't know how to debug further.

firejail latest master / 0.9.53 on Fedora 27, works with `--noprofile`.

**Comment by smitsohu** [comment]
Thanks for your report. Could you please check briefly if it works when you replace `seccomp` with the long `seccomp.drop` line from [qutebrowser profile](https://raw.githubusercontent.com/netblue30/firejail/ca3964fed3f141e75bf396defaec3dca543ce49f/etc/qutebrowser.profile)?

**Comment by johnp** [comment]
No, doesn't work, but I just saw that a fresh profile works fine. I'll check my preferences to see what's triggering the issue...

**Comment by johnp** [comment]
I verified via mozregression that bug 140162 is the issue. ([pushlog](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=cba9a29be139a663869a2c26557fd527a6981407&tochange=bd7ff5744eb29e105b7b3c37cb5f46164fa11ef4)) 
I haven't been able to identify what exactly in my profile is causing the issue to manifest, still trying though.

**Comment by SpotComms** [comment]
We'll probably eventually need to remove` seccomp` and add `caps.keep sys_chroot,sys_admin` like chromium.profile as mentioned in #1414.

**Comment by smitsohu** [comment]
It seems that three options are causing problems: `noroot`, `seccomp` and `apparmor`. `seccomp` works just fine on some distributions (arch, debian) and is breaking firefox on others (fedora, ubuntu), depending on how distributions handle unprivileged user namespaces.

@johnp Can you please comment out these lines in your firefox profile and give it a try? Instead of disabling `seccomp` altogether, you can also replace it with this long line:
```
seccomp.drop @clock,@cpu-emulation,@debug,@module,@obsolete,@raw-io,@reboot,@resources,@swap,acct,add_key,bpf,fanotify_init,io_cancel,io_destroy,io_getevents,io_setup,io_submit,ioprio_set,kcmp,keyctl,mount,name_to_handle_at,nfsservctl,ni_syscall,open_by_handle_at,personality,pivot_root,process_vm_readv,ptrace,remap_file_pages,request_key,setdomainname,sethostname,syslog,umount,umount2,userfaultfd,vhangup,vmsplice
```
If you want to double-check: Adding `chroot` to the `seccomp.drop` line should crash firefox again.

**Comment by johnp** [comment]
@smitsohu Yes, works with `noroot`, `seccomp` and `apparmor` commented out and with the `seccomp.drop` line together with `noroot` and `apparmor` commented out. Adding `chroot` makes Firefox unusable again.

**Comment by m0n5t3r** [comment]
on Ubuntu 16.04 (and firejail 0.9.52 from ppa:deki/firejail) I had to drop pivot-root from the seccomp line above (original issue: I was seeing blank windows, closing them didn't end the firefox program, but it would crash later in libmozsandbox.so - I assume it does some sort of chroot-ing on its own and needs that capability).

it works for me with noroot in there, btw. (and there is no apparmor line in my version of firejail)

**Comment by smitsohu** [comment]
Thanks @m0n5t3r for the data point.

With regard to the Apparmor policy: [Firefox crashes](https://searchfox.org/mozilla-central/source/security/sandbox/linux/launch/SandboxLaunch.cpp#473) when it can't write to /proc/[pid]/uid_map, gid_map or setgroups.

**Comment by Vincent43** [comment]
> With regard to the Apparmor policy: Firefox crashes when it can't write to /proc/[pid]/uid_map, gid_map or setgroups.

That never happened to me. Is this new nightly thing?

**Comment by smitsohu** [comment]
@Vincent43 Yep, it's only Nightly (for now).

**Comment by Vincent43** [comment]
Ok, we can fix it with adding `owner /proc/[0-9]*/{uid_map,gid_map,setgroups} w,` to firejail apparmor profile.

**Comment by Vincent43** [comment]
I think we should add `ignore noroot,seccomp,shell` to firefox dev/nightly. After Firefox 60 release we can remove those from firefox profile.

**Comment by smitsohu** [comment]
It should be sufficient to either disable `noroot` or `shell none`, I guess we have a choice here. Also since most of `seccomp` works well, how about a `seccomp.drop` line in firefox-common? 

Btw, I still see problems only with chroot and have not been able to replicate the issue with pivot_root yet. Maybe I'm escaping a condition?

**Comment by Vincent43** [comment]
I don't think `seccomp` is worth to keep when firefox rolls its own seccomp filter (and this is probably reason why it's breaking). We can trust upstream knowing which calls should be allowed. We don't use it in chromium profile already.

In my understanding `noroot`behavior differs on various distros (on some doesn't cause problems) so maybe disabling `shell` is better option.

**Comment by Fred-Barclay** [comment]
I'd prefer to have at least `seccomp.drop`. We may have to get rid of it entirely some day for Firefox, but for now I think we ought to keep seccomp around in some form.

We should probably drop `shell none` instead of `noroot` too. We can always control exactly which shells are present, and what can be called through them, with `private-bin` even without `shell none`.

**Comment by smitsohu** [comment]
Interestingly there is a similar issue with Qt Webengine. The combination of `shell none`, `noroot` and `seccomp` causes Webengine to crash in case of Akregator (Ubuntu, Fedora or `sudo sysctl kernel.unprivileged_userns_clone=1`). In the end the app starts successfully, but setup of the built-in sandbox seems to be incomplete. The backtrace points to a function that wants to write to files in /proc/[PID] (if I remember it right uid_map and gid_map).

Launching Firefox >=60 (or Akregator) as `firejail --noprofile --noroot --shell=none firefox` fails because the apps suspect they run as SUID:
```
smitsohu@home:/opt/firefox$ firejail --noprofile --noroot --shell=none ./firefox
Parent pid 2687, child pid 2688
Child process initialized in 37.08 ms

(firefox:2): Gtk-WARNING **: This process is currently running setuid or setgid.
This is not a supported use of GTK+. You must create a helper
program instead. For further details, see:

    http://www.gtk.org/setuid.html

Refusing to initialize GTK+.

Parent is shutting down, bye...
smitsohu@home:/opt/firefox$ 
```

@netblue30 Is it possible all these problems are caused by Firefox/Akregator somehow inheriting the non-dumpable provisions of Firejail? It seems to be primarily a problem of `--shell=none`. Should we regard it as a security add-on that's worth working around or rather as a bug?

**Comment by smitsohu** [comment]
@netblue30 Ok, it looked up the definition of the warning message cited above: https://github.com/GNOME/gtk/blob/acb950ffb5a8a120827dad63860cf600aefb0dcb/gtk/gtkmain.c#L319

Nothing to do with dumpable, but a bug I guess?

**Comment by Fred-Barclay** [comment]
This should hopefully be fixed in upstream now.
`seccomp` was replaced with the string @smitsohu provided in https://github.com/netblue30/firejail/issues/1765#issuecomment-373925382

After a brief [discussion](https://github.com/netblue30/firejail/pull/1865#issuecomment-379408569), `pivot_root` was left in as neither @smitsohu nor I were able to reproduce any issues with it (I tested firefox nightly and beta on Mint 18.2).

`shell none` was also commented out.

**Comment by pizzadude** [comment]
@Fred-Barclay it isn't fixed for me

I had to fix it manually, by commenting out:
apparmor
nogroups
noroot

and disable-mnt because i have downloads folder in /media but that's unrelated

**Comment by Fred-Barclay** [comment]
@pizzadude we had to change a few other settings for apparmor. Can you build from source and test again?
Thanks!
Fred

**Comment by pizzadude** [comment]
@Fred-Barclay 
It works fine when I comment tracelog out. It seems tracelog is the culprit. I'm not sure why. (not a programmer)
