### ISSUE TITLE
Vim contrib files do not follow the DESTDIR option in make install

### ISSUE THREAD

**Issue by corecontingency** [netblue30/firejail#3396]
Broken in commit [944049c](https://github.com/netblue30/firejail/commit/944049c4df9aec50cc7bc3ac7724e1d5dbf5d551).

The makefile is installing to `$(datarootdir)` instead of` $(DESTDIR)`.

This breaks the [AUR package](https://aur.archlinux.org/packages/firejail-git), as it tries to to install the vim files to `/usr/share/vim/vimfiles/ftdetect/` instead of the package working directory. See:

```
install -c -m 0755 contrib/sort.py /home/user/Downloads/firejail-git/pkg/firejail-git//usr/lib/firejail/.
install -c -m 0755 contrib/syscalls.sh /home/user/Downloads/firejail-git/pkg/firejail-git//usr/lib/firejail/.
install -c -m 0644 contrib/vim/ftdetect/firejail.vim /usr/share/vim/vimfiles/ftdetect/.
install: cannot create regular file '/usr/share/vim/vimfiles/ftdetect/./firejail.vim': Permission denied
make[1]: *** [Makefile:104: realinstall] Error 1
make[1]: Leaving directory '/home/user/Downloads/firejail-git/src/firejail-git'
make: *** [Makefile:150: install] Error 2
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by rusty-snake** [comment]
Should be fixed with 452fc93.

**Comment by glitsj16** [comment]
For me the build from git master is still broken, even with https://github.com/netblue30/firejail/commit/452fc93a91b2e9dc6e9bee52d3bf10d0fb9f6616. I use a custom-made PKGBUILD on Arch, so I hadn't looked at the one from AUR in a while. What I find odd is it tries to install vim files in the first place, because the AUR PKGBUILD doesn't use the `--enable-contrib-install` flag AFAICT and I thought the default is not to.

Even when adding `--datarootdir=/usr/share --enable-contrib-install` make install still fails to find the vim files and aborts. The only way I can unbreak the build currently is by explicitly adding `--disable-contrib-install`, otherwise I keep seeing **Install contrib scripts: yes** in the configuration options output.

Together with #3393 it sure looks like our Makefile.in needs some love... @netblue30?

**Comment by corecontingency** [comment]
Can confirm the AUR package is still failing:
```

install -c -m 0755 contrib/sort.py /home/user/Downloads/firejail-git/pkg/firejail-git//usr/lib/firejail/.
install -c -m 0755 contrib/syscalls.sh /home/user/Downloads/firejail-git/pkg/firejail-git//usr/lib/firejail/.
install -c -m 0644 contrib/vim/ftdetect/firejail.vim /home/user/Downloads/firejail-git/pkg/firejail-git//usr/share/vim/vimfiles/ftdetect/.
install: cannot create regular file '/home/user/Downloads/firejail-git/pkg/firejail-git//usr/share/vim/vimfiles/ftdetect/.': No such file or directory
make[1]: *** [Makefile:104: realinstall] Error 1
make[1]: Leaving directory '/home/user/Downloads/firejail-git/src/firejail-git'
make: *** [Makefile:150: install] Error 2
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by rusty-snake** [comment]
```patch
diff --git a/Makefile.in b/Makefile.in
index 9e026318..e7ccba14 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -104,6 +104,8 @@ ifeq ($(HAVE_CONTRIB_INSTALL),yes)
        install -c -m 0755 contrib/fj-mkdeb.py $(DESTDIR)/$(libdir)/firejail/.
        install -c -m 0755 contrib/sort.py $(DESTDIR)/$(libdir)/firejail/.
        install -c -m 0755 contrib/syscalls.sh $(DESTDIR)/$(libdir)/firejail/.
+       install -m 0755 -d $(DESTDIR)/$(datarootdir)/vim/vimfiles/ftdetect/.
+       install -m 0755 -d $(DESTDIR)/$(datarootdir)/vim/vimfiles/syntax/.
        install -c -m 0644 contrib/vim/ftdetect/firejail.vim $(DESTDIR)/$(datarootdir)/vim/vimfiles/ftdetect/.
        install -c -m 0644 contrib/vim/syntax/firejail.vim $(DESTDIR)/$(datarootdir)/vim/vimfiles/syntax/.
 endif

```

**Comment by glitsj16** [comment]
@rusty-snake Above patch returns 'Makefile:107: *** missing separator.  Stop.'

**Comment by corecontingency** [comment]
Seems to work fine for me. I didn't use the patch though, just edited the changes into my fork of firejail and switched the URL in the PKGBUILD to my [repo](https://github.com/corecontingency/firejail).

**Comment by glitsj16** [comment]
Let me clean things up and try again...

**Comment by glitsj16** [comment]
Progress:
Works: ./configure --prefix=/usr --enable-apparmor
Works: ./configure --prefix=/usr --enable-apparmor --enable-contrib-install
Breaks: ./configure --prefix=/usr --enable-apparmor --disable-contrib-install

So something still needs attention IMO, at least if we want the configure flags to work as advertised. @corecontingency Does it work for you when using the --disable-contrib-install flag?

**Comment by corecontingency** [comment]
> Does it work for you when using the --disable-contrib-install flag?

Yes, it seems to work, and build the package properly. Changed this line in the PKGBUILD from:
`./configure --prefix=/usr --enable-apparmor`
to
`./configure --prefix=/usr --enable-apparmor --disable-contrib-install`

And switched the URL line to:
`source=("${pkgname}::git+https://github.com/corecontingency/firejail.git")`
which is master + rusty-snake's changes.

Let me try those other options.

**Comment by glitsj16** [comment]
@corecontingency Thanks for the heads-up. I messed too much with my setup here and need sleep :-) Sorry for the noise.

**Comment by rusty-snake** [comment]
travis passing

**Comment by glitsj16** [comment]
@corecontingency The issue should be fixed now so we can close here. Feel free to reopen if needed. And thanks again for your input!
