### ISSUE TITLE
element-desktop not starting

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#3586]
I received a [bug report](https://bugs.debian.org/968382) that element-desktop is not starting with firejail (0.9.62) and was able to reproduce it.
The problem (at least for me) was "nodbus" from electron.profile.
With "ignore nodbus" it's successfully starting.

With the new dbus changes in master I'm currently not sure what the best fix would be.
"ignore dbus-user" and "ignore dbus-system", or is there a better way to allow narrower dbus access?

**Comment by kortewegdevries** [comment]
It launches fine under current profiles of 0.9.62.2-1 (Ubuntu groovy proposed) _without_ `ignore nodus`. 

This 

> ```
50:0814/095134.384213:FATAL:platform_shared_memory_region_posix.cc(254)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
```
appears  only when `--no-sandbox` is used and even with `ignore nodbus` included in Element profile it doesn't launch with `--no-sandbox` (the screen stays white).

**Comment by reinerh** [comment]
Sorry, I forgot to mention that `--no-sandbox` is used.

**Comment by kortewegdevries** [comment]
#https://github.com/vector-im/element-web/issues/13171#issuecomment-650806459

**Comment by reinerh** [comment]
@kortewegdevries I also see the white screen after starting.
But with `nodbus` it's not even fully starting up here (there is no tray icon). Did you observe the same?

**Comment by kortewegdevries** [comment]
> @kortewegdevries I also see the white screen after starting.
> But with `nodbus` it's not even fully starting up here (there is no tray icon). Did you observe the same?

No in my case it starts in tray, doesn't expand to windowed/full screen until toggled from tray and stays white thereafter.

**Comment by reinerh** [comment]
It might be related to my window manager, but with `nodbus` I don't get any tray icon (so I can't open the element window).

> (element-desktop:12): libappindicator-WARNING **: 10:20:24.734: Unable to get the session bus: Could not connect: No such file or directory
> 
> (element-desktop:12): LIBDBUSMENU-GLIB-WARNING **: 10:20:24.734: Unable to get session bus: Could not connect: No such file or directory

But maybe there is also a different issue, as the bug reporter had different messages.

**Comment by kortewegdevries** [comment]
Those two messages appear for me regardless of `--no-sandbox` under firejail; I don't know if they are harmless or actually break some functionality (I don't use element), I'm under Xfce...

**Comment by kortewegdevries** [comment]
Opened 14982 on element-web regarding this... from the recent update of Element 1.7.4 the tray icon has gone...

**Comment by rusty-snake** [comment]
Tray icon would be the following AFAIK, see #3540.

```
dbus-user filter
dbus-user.talk org.freedesktop.StatusNotifierItem
dbus-user.talk org.kde.StatusNotifierWatcher
```

**Comment by kortewegdevries** [comment]
No, I meant it doesn't even show _without_ firejail, and I was testing it on 0.9.62.4-2 (is it?)... Debian people can't launch element under firejail... this is a chromium bug since version 80/81.something, the chromium bug tracker has an issue, they suggested --no-xshm. ----ignore-gpu-blacklist, env variables etc. none of which work for me when used with --no-sandbox on Ubuntu groovy/Debian bullseye.

People using Ubuntu can launch it fine under firejail (0.9.62.4-2) without any modifications, since they don't need to use --no-sandbox, Debian can't...

**Comment by rusty-snake** [comment]
still an issue?

**Comment by reinerh** [comment]
Unfortunately yes. Checked again with Element 1.7.13:
```
$ firejail element-desktop
...
[10:1110/113057.289531:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Element/chrome-sandbox is owned by root and has mode 4755.
```
```
$ firejail element-desktop --no-sandbox
...
/home/reiner/.config/Element exists: no
/home/reiner/.config/Riot exists: no
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform

(element-desktop:10): libappindicator-WARNING **: 11:31:44.310: Unable to get the session bus: Could not connect: Permission denied

(element-desktop:10): LIBDBUSMENU-GLIB-WARNING **: 11:31:44.310: Unable to get session bus: Could not connect: Permission denied
[57:1110/113144.388034:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
```
(in this case there is not even a tray icon showing up)

After commenting `dbus-user none` in electron.profile (used by the Element profile):
```
$ firejail element-desktop --no-sandbox
...
/home/reiner/.config/Element exists: no
/home/reiner/.config/Riot exists: no
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
[56:1110/113309.295246:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permis
```
The tray icon is now showing up, and you can open the main window. But the window only stays white.

**Comment by kortewegdevries** [comment]
On Tue, 10 Nov 2020 02:35:00 -0800
Reiner Herrmann <notifications@github.com> wrote:

> Unfortunately yes. Checked again with Element 1.7.13:
> ```
> $ firejail element-desktop
> ...
> [10:1110/113057.289531:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Element/chrome-sandbox is owned by root and has mode 4755.
> ```
> ```
> $ firejail element-desktop --no-sandbox
> ...
> /home/reiner/.config/Element exists: no
> /home/reiner/.config/Riot exists: no
> Starting auto update with base URL: https://packages.riot.im/desktop/update/
> Auto update not supported on this platform
> 
> (element-desktop:10): libappindicator-WARNING **: 11:31:44.310: Unable to get the session bus: Could not connect: Permission denied
> 
> (element-desktop:10): LIBDBUSMENU-GLIB-WARNING **: 11:31:44.310: Unable to get session bus: Could not connect: Permission denied
> [57:1110/113144.388034:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
> ```
> (in this case there is not even a tray icon showing up)
> 
> After commenting `dbus-user none` in electron.profile (used by the Element profile):
> ```
> $ firejail element-desktop --no-sandbox
> ...
> /home/reiner/.config/Element exists: no
> /home/reiner/.config/Riot exists: no
> Starting auto update with base URL: https://packages.riot.im/desktop/update/
> Auto update not supported on this platform
> [56:1110/113309.295246:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permis
> ```
> The tray icon is now showing up, and you can open the main window. But the window only stays white.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/netblue30/firejail/issues/3586#issuecomment-724616194

For this error when doing `firejail <electron-app>`

```
[14:0611/105406.114486:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/atom/chrome-sandbox is owned by root and has mode 4755.
```

I don't think workarounds like these https://github.com/netblue30/firejail/commit/cb6799523085ddc7caf57b235514e6865a4caeaa, force nonewprivs, seccomp, syscall etc. work with more recent electron versions (tested with element-desktop on Debian; which uses electron 10.1.3 I think). This won't be restricted to element-desktop only once respective developers starts gradually bumping their electron versions.

Then you are forced to use `firejail <electron-app> --no-sandbox` which now again doesn't work:

```
[57:1110/113144.388034:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
```

So baseline (1) turn the sysctl knob + use firejail, or (2) use those electron apps without firejail and rely on chromium's sandbox. In that case I recommend adding a wiki/sticky entry noting the implications of turning the sysctl knob for unpriv user ns clone, `--no-sandbox` or relying on chromium sandbox vs. firejail from a functional perspective. See here https://github.com/netblue30/firejail/issues/1347 and here https://github.com/netblue30/firejail/issues/554. 

Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1035803
Electron: https://github.com/electron/electron/issues/22775#issuecomment-616023334 (None of the workarounds work; only works in the remote x session case.)

**Comment by kortewegdevries** [comment]
> So baseline (1) turn the sysctl knob + use firejail,

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898446#117 https://salsa.debian.org/kernel-team/linux/-/commit/a381917851e762684ebe28e04c5ae0d8be7f42c7

Once the kernel comes I'll check it and also Element is using electron 11 now.

**Comment by rusty-snake** [comment]
> ```
> $ firejail element-desktop
> ...
> [10:1110/113057.289531:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Element/chrome-sandbox is owned by root and has mode 4755.
> ```

Fixed by #3807.

> The tray icon is now showing up,

Tray-icon researches: #3774.
However element-desktop is now affected by #1137 if I'm right.

**Comment by reinerh** [comment]
> > ```
> > $ firejail element-desktop
> > ...
> > [10:1110/113057.289531:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Element/chrome-sandbox is owned by root and has mode 4755.
> > ```
> 
> Fixed by #3807.

With `kernel.unprivileged_userns_clone = 0` it still does not want to start in firejail:
> The setuid sandbox is not running as root. Common causes:
>   * An unprivileged process using ptrace on it, like a debugger.
>   * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
> Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

After setting `kernel.unprivileged_userns_clone` to 1, it's successfully starting up, and even the tray icon is showing up here.
Thanks a lot for your work on that!

> However element-desktop is now affected by #1137 if I'm right.

I can't confirm that here. Tray icon still works fine with `private-tmp`.

**Comment by rusty-snake** [comment]
> > > ```
> > > $ firejail element-desktop
> > > ...
> > > [10:1110/113057.289531:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Element/chrome-sandbox is owned by root and has mode 4755.
> > > ```
> > 
> > 
> > Fixed by #3807.
> 
> 
> With `kernel.unprivileged_userns_clone = 0` it still does not want to start in firejail:

Have you set `force-nonewprivs yes`?

**Comment by reinerh** [comment]
> > With `kernel.unprivileged_userns_clone = 0` it still does not want to start in firejail:
> 
> Have you set `force-nonewprivs yes`?

No, I have it at default (commented out / disabled).
