### ISSUE TITLE
VSCodium doesn't work with seccomp in profile

### ISSUE THREAD

**Issue by mYnDstrEAm** [netblue30/firejail#4896]
### Description
After upgrading firejail and firejail-profiles from Debian backports it didn't launch anymore.
VsCodium only launches if I comment out seccomp in the profile.

* Maybe the profile or firejail needs to be changed.
* I also have `noblacklist ${HOME}/.config/VSCodium` in code.local and don't know if it would be useful to add this.
* If disabling seccomp is needed: how can this be done from code.local so the code.profile remains unchanged?

### Steps to Reproduce

1. Try to launch VSCodium with firejail 0.9.66 on Debian11

### Expected behavior
Launch VSCodium

### Actual behavior
Doesn't launch and doesn't show any error window or output in the console.

### Environment
- Linux distribution and version: Debian11/KDE with Wayland
- Firejail version: 0.9.66

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [x] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

**Comment by rusty-snake** [comment]
Duplicate of #4408

**Comment by rusty-snake** [comment]
Fixed by 8f867d029a6ae7b757190d9f273886d4bbc1344b

**Comment by rusty-snake** [comment]
> If disabling seccomp is needed: how can this be done from code.local so the code.profile remains unchanged?

`ignore seccomp`

**Comment by GreatBigWhiteWorld** [comment]
> Fixed by [8f867d0](https://github.com/netblue30/firejail/commit/8f867d029a6ae7b757190d9f273886d4bbc1344b)

I am still having this issue despite having the latest version of firejail, which includes 
```
# Redirect
include electron.profile 
```
in code.profile.
