### ISSUE TITLE
the UID and GID change to root in the sandbox after firejail exit

### ISSUE THREAD

**Issue by requiredregistration** [netblue30/firejail#513]
i `firejail --private=DIR` to start a firejail shell, i run the application and it creates its dot configuration directory and .bash_history, and when i exit the shell, the configuration directory's and the history file's UID and GID change to root

**Comment by netblue30** [comment]
What kernel version  are you using? Run a "uname -r"

**Comment by requiredregistration** [comment]
4.5.4

**Comment by netblue30** [comment]
Yes, I've seen it before on older kernels, I assumed there is a problem with the kernel. Does it happen all the time? Are you using 0.9.38 or the latest in git?

**Comment by requiredregistration** [comment]
it happens always and i use git.

**Comment by netblue30** [comment]
Create a brand new directory and try it:
$ rm -fr ~/DIR
$ mkdir ~/DIR
$ firejail --private=~/DIR
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 11794, child pid 11795

Child process initialized
$ ls -al
total 48
drwxr-xr-x 3 netblue netblue  4096 May 15 08:11 .
drwxr-xr-x 3   65534   65534    60 May 15 08:11 ..
-rw-r--r-- 1 netblue netblue  3515 May 15 08:11 .bashrc
drwxr-xr-x 3 netblue netblue  4096 May 15 08:11 .config
-rw------- 1 netblue netblue 35351 May 15 08:11 .Xauthority
$ 
`````
I am running on the regular 4.5 kernel from Debian backports:
`````
$ uname -r
4.5.0-0.bpo.1-amd64
`````
Is it a kernel you compiled? What distro are you running?

**Comment by requiredregistration** [comment]
the directory was never a problem. something is wrong in firejail and/or the kernel.

this is the config of the kernel, https://git.archlinux.org/svntogit/packages.git/tree/trunk/config.x86_64?h=packages/linux

**Comment by requiredregistration** [comment]
also, the [grsecurity kernel config](https://git.archlinux.org/svntogit/community.git/tree/trunk/config.x86_64?h=packages/linux-grsec).

you must first test with all the latest versions of everything, compiling your own builds where required, and using the arch linux distribution for that.

**Comment by netblue30** [comment]
I have no idea what's going on, I cannot reproduce it on Debian/Ubuntu. I've seen something similar a long time ago on older kernels, it used to come and go.

**Comment by requiredregistration** [comment]
test also with and without CONFIG_USER_NS

**Comment by netblue30** [comment]
Try the new version I just released.

**Comment by requiredregistration** [comment]
i tested with 4.5.4 (# CONFIG_USER_NS is not set) and 4.5.5 (grsecurity, CONFIG_USER_NS=y).

the problem was not solved with the new version of firejail, and with the grsecurity kernel the result is files with this stat(1):

(0400/-r--------) Uid: (65534/ UNKNOWN)  Gid: (65534/ UNKNOWN)

**Comment by netblue30** [comment]
I've just installed Arch and it seems to be working fine.
