### ISSUE TITLE
Preventing mouse pointer being locked into firejail Xephyr?

### ISSUE THREAD

**Issue by laniakea64** [netblue30/firejail#557]
**Environment**
Lubuntu 14.04
firejail self build from https://github.com/netblue30/firejail/commit/a81568d4f03a12817ab2b0ad6d52159eb5a9eb10
Firefox 46.0.1

**Steps to reproduce**
1) start Openbox in firejail Xephyr, with firefox profile: `firejail --ignore=noroot --profile=~/.config/firejail/firefox.profile --x11 openbox` (or even: `firejail --noprofile --x11 openbox`)
2) from Openbox menu, open Terminal emulator, from there run Firefox
3) type Ctrl-Shift-J to open Firefox's Browser Console

Now the mouse pointer is locked inside the Xephyr, the only way I've found to get it back is to switch to a different tty (Ctrl-Alt-F1) and kill the Xephyr PID with SIGINT. :confused: 

Can this sort of mouse pointer "stealing" be prevented, either by firejail or some other means?
Or is there some other (guaranteed) way to get the mouse pointer back in these situations without switching tty or quitting the Xephyr?

Thanks in advance.

**Comment by netblue30** [comment]
It looks like Xephyr grabs the keyboard and the mouse when you press Ctrl-Shift. If you press Ctrl-Shift again it will release the mouse. According to these http://superuser.com/questions/280375/how-to-change-default-behavior-of-xephyr-for-capturing-and-releasing-keyboard-mo people, it is hardcoded in Xephyr.

Maybe Ctrl-Shift can be redirected to something else using xmodmap utility, but in that case ctrl-shift-J will not work in Firefox.

**Comment by laniakea64** [comment]
Good to know that it's not the sandboxed application doing this :+1: 
I see now that Ctrl-Shift is what's grabbing the mouse, but Ctrl-Shift again does **not** release the mouse in a firejail Xephyr.  However, the second Ctrl-Shift does correctly release the mouse in a non-firejail Xephyr.
Some investigation points to the use of the Xephyr command-line option `-title` as the culprit.

As a work-around, can firejail please add an option to disable the use of the `-title` Xephyr command-line option?

**Comment by netblue30** [comment]
I can exit with a single Ctrl-Shift when using Firejail. I'll document the behavior, the title stays.

**Comment by laniakea64** [comment]
> I can exit with a single Ctrl-Shift when using Firejail.

I'm hitting this problem even in the Lubuntu 16.04 live CD environment, specifying `-title` is preventing Ctrl-Shift from releasing mouse and keyboard.
How are you getting it to work?

**Comment by netblue30** [comment]
I'll bring something in shortly.

**Comment by netblue30** [comment]
Fixed! Install the version from git, and edit /etc/firejail/firejail.config file. You need to add "xephyr-window-title no" at the end.

**Comment by laniakea64** [comment]
Nice :smiley: Confirmed fixed by https://github.com/netblue30/firejail/commit/ecaf0cb4edcc9f216af7c0bfd238db6b2516c799, thanks!

**Comment by netblue30** [comment]
No problem, if you find out anything else just let me know.

**Comment by alextrekov3307** [comment]
This problem is still present. Why isn't xephyr-window-title a valid command line argument?
