### ISSUE TITLE
Unable to output sound with PulseAudio 7.0

### ISSUE THREAD

**Issue by pyamsoft** [netblue30/firejail#69]
With the upgrade to PulseAudio 7.0 on Archlinux, audio in Chromium 45 and other applications which use pulseaudio fail to work properly.

In the case of chromium, launching with the default sandbox and no profile/seccomp chomium will launch and instantly report a failure that it is unable to open a slave. Firejail worked fine on PulseAudio 6.

Aside from the debug output of firejail the only other noteworthy output that Chromium spews is the failure to open a slave, which I have found is something dealing with ALSA on the system.

A similar outcome can be observed when launching firefox with no profile, as well as any other application which may use pulseaudio.

Oddly enough, things like Steam work fine at outputting audio via Pulse, but seem to fail when attempting to record audio input via a microphone in firejail, even though this functionality was working under PulseAudio 6.

Apologies for the very vague bug report, I am rather confused about where the source of the problem exactly is.

Firejail version 0.9.30
PulseAudio version 7.0

**Comment by netblue30** [comment]
I'll leave it for two weeks for Arch to stabilize, and I'll fix it. Thanks

**Comment by RoBi89** [comment]
Having the same issue. Check here: https://bugs.freedesktop.org/show_bug.cgi?id=92141 to take a look at what I've already found out with the help of the pulseaudio developers.

Starting firejail deletes pulseaudio shm files in /dev/shm causing it to stop working.

**Comment by netblue30** [comment]
No, for a regular user firejail doesn't touch shm. Try like this:
`````
$ touch /dev/shm/testfile
$ ls /dev/shm
firejail  testfile
`````
I have created a file, now I start firejail:

$ firejail 
Reading profile /etc/firejail/generic.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-history.inc

** Note: you can use --noprofile to disable generic.profile **

Parent pid 6856, child pid 6857
Child process initialized
$ ls /dev/shm
firejail  testfile
`````
The file is still visible in the sandbox. Now I exit firejail and check the file again:
`````
$ exit
exit

parent is shutting down, bye...
l$ ls /dev/shm
firejail  testfile
$ 
`````
After closing the sandbox, the file is still there.

Firejail modifies /dev/shm in two cases: if the sandbox is run as root, or if --private-dev option is used. In both cases a tmpfs filesystem is mounted on top of /dev/shm directory. Processes running outside the sandbox will see the real /dev/shm. Firejail never deletes files from /dev/shm directory.

**Comment by RoBi89** [comment]
I start firejail with --seccomp enabled, could this be the cause?

Because I know one thing for sure, it definitely seems to be firejail that deletes these shm files. I have been trying to find where exactly the issue lies, and unless I run 

    firejail --seccomp firefox 

which is the default way I run firefox, pulseaudio does not have issues. Starting firefox without firejail does not cause any problems either. I'm not running firejail as root either.

Have you taken a look at the link I provided? Maybe that could help clear things up a bit.

**Comment by pyamsoft** [comment]
Allow me to comment on my findings regarding the progress in this thread.

All of the following is tested and ran as a normal, non-privileged user.
First the initial problem, which I have noticed:

Some incompatability between PulseAudio 7 and firejail prevent it from outputting audio in programs that used to function successfully like chromium and firefox. Both chromium and firefox were launched with the following options to test this:

    firejail --noprofile --debug chromium

    firejail --noprofile --debug firefox

This should, I believe, launch firejail with the least restrictive setup possible. No seccomp, no capability dropping, no blacklisting of directories. The debug messages also reflect this, and never once mention tampering with /dev/shm.

After launching:
    firejail --noprofile --debug chromium

There are infact, no pulse-shm-* files located in the /dev/shm directory. Before launching, on my specific system, there we about 4 instances of various shm files. Restarting pulseaudio via:
    systemctl --user restart pulseaudio

restores these pulse-shm-* files, but does not restore sound output. 

However, this does not mean that firejail is destroying /dev/shm. When launching keepass, which does not use pulseaudio in any way, using firejail, the /dev/shm directory stays intact.

Do note, that applying the pulseaudio work around of adding srbchannel=no into the default.pa file does appear to resolve the issue, although it is not the best solution as it does not allow one to take advantage of the progress in pulseaudio development with the newer version 7.

As a tl;dr

     # /dev/shm has pulse-shm-* files
     firejail --noprofile --debug chromium
     
     #  /dev/shm now empty, except for a firejail directory, pulseaudio does not work
     firejail --noprofile --debug keepass (or bash)
     
     # /dev/shm still contains all pulse-shm-* files
     #  srbchannel=no "fixes" pulseaudio, but is far from ideal of a solution.

     # Launching chromium without firejail works fine, as expected.

**Comment by netblue30** [comment]
> ... applying the pulseaudio work around of adding srbchannel=no into the default.pa file does appear to resolve the issue

OK, there seems to be a workaround. Use it until I get a chance to find the problem. I am installing Arch right now.

**Comment by RoBi89** [comment]
Just a little advice: If this is just about fixing the bug, you might want to use antergos instead of arch. It's basically the same but you don't have the hassle of dealing with the arch install.

**Comment by netblue30** [comment]
Thanks for the antergos idea!

**Comment by Utini2000** [comment]
Evolution Installer is another solution for easy and quick (5mins) arch installation.

**Comment by Utini2000** [comment]
writing srbchannel = no into the /etc/pulse/default.pa makes it impossible to start the daemon.

**Comment by pyamsoft** [comment]
Please note that the srbchannel option needs to be added as described in the pulseaudio bugtracker thread linked above, not simply written into the file.

If the proper addition of the srbchannel option prevents pulseaudio startup, that it a bug for pulseaudio, not firejail.

**Comment by netblue30** [comment]
srbchannel=no crashes pulseaudio. With pulseaudio out of the picture, the system defaults to ALSA. I got "firejail firefox" running fine after adding "srbchannel=no" in /etc/pulse/default.pa and system restart. The inconvenience is that I had to replace pavucontrol with gnome-alsamixer.

I'll look to see what is going on. Antegos/Arch is running fine here!

**Comment by netblue30** [comment]
I added a description of the problem and workarounds on the main page of the project.

**Comment by amarildojr** [comment]
Hello,

Is there an expected time for this issue to be resolved?

Regards,
Amarildo

**Comment by netblue30** [comment]
Unfortunately this is a PulseAudio 7.0 bug. I don't see any way to get around it at sandbox level. There are two workarounds described in "known bugs" section here: https://github.com/netblue30/firejail

I'll keep this discussion open in case somebody figures it out.

**Comment by amarildojr** [comment]
Hi,

Yes, the fixed seems to be working, and it doesn't seem to be breaking Pulse :)

Have you contacted pulseaudio developers?

Thanks and keep up the good work,
Amarildo

**Comment by tanuk** [comment]
A PulseAudio developer here. I'd be interested to hear more details about why you think this is a PulseAudio bug.

**Comment by tanuk** [comment]
Hmm... I have a likely explanation for the bug. Whenever PulseAudio creates a new shm file, it also cleans up any files that are left by crashed processes that didn't clean up the files they created. Each shm file contains the pid of the process that created it. The cleanup is triggered, if kill(pid, 0) fails with ESRCH, that is, if the pid does not exist. If firejail creates a new pid namespace, then processes outside the sandbox aren't visible to processes in the sandbox, and a sandboxed process will "clean up" all shm files.

So yes, this is a PulseAudio bug after all. With pid namespaces, we can't assume that a process is dead if kill() fails with ESRCH.

This will be resolved when we get memfd support in PulseAudio (currently being worked on). I'm not sure that it will be ready before the next release, so some other fix may be needed. I don't yet what that fix might be, though. Not cleaning up the shm files isn't really a good solution.

**Comment by amarildojr** [comment]
@tanuk 

>I'm not sure that it will be ready before the next release, so some other fix may be needed

Hi. There is a fix on the main page that currecntly works. I read some people saying it breaks pulse, but for what I could see everything is working fine here. Ardour, Steam, pavucontrol, simplescreenrecorder, all working fine.

> Not cleaning up the shm files isn't really a good solution
Could elaborate?

**Comment by Utini2000** [comment]
@tanuk is there a way to manually clean up shm files ? thanks !

**Comment by netblue30** [comment]
Hi tanuk, thank you for your help. memfd is fine, we can wait until then. There is a workaround by disabling shm in PulseAudio - I guess in this case the client/server communication goes over the Unix socket. And there is also ALSA used as backup by Firefox and most other programs - I just have to explain to users to turn up the volume using alsamixer or some equivalent.

**Comment by tanuk** [comment]
> > Not cleaning up the shm files isn't really a good solution

> Could you elaborate?

I mean that if it's hard to figure out which shm files are safe to remove, we could solve this by simply not cleaning up leaked shm files, but leaking resources is not cool.

> is there a way to manually clean up shm files ?

You can simply remove the files from /dev/shm, if you can figure out which of the files are not being used any more.

@netblue30 If the workaround isn't applied automatically, a very big portion of your users will waste time wondering why their audio doesn't work, and probably not everyone will find the workaround. Are you really ok with that?

When firejail starts, maybe it could automatically copy ~/.config/pulse/client.conf to a temporary location, add "enable-shm = no" to the copy, and set the PULSE_CLIENTCONFIG environment variable to point to the modified configuration file?

**Comment by netblue30** [comment]
@tanuk Thanks for the idea, I'll try it out.

**Comment by netblue30** [comment]
OK, the fix is in. So far it seems to be working on Debian jessie and Antergos/Arch. Let me know if you see any problems. Thanks!

**Comment by Utini2000** [comment]
Uhm as I am relatively new to linux (and arch): I am not getting a firejail update on arch so that I could test the new fix?

**Comment by amarildojr** [comment]
@Utini2000 I think it's the same fix that is present on the main page here. 

If you want, you could contact the AUR maintainer so that he/she can update fifrejail for you. Or, you download the PKGBUILD and just edit it so that it fetches the new source (if there's one).

**Comment by emacsomancer** [comment]
updated to the latest git. the fix works for a while, but eventually i run into the same issue (pavucontrol can't connect, keyboard volume controls stop working), and have to "pulseaudio -k" and restart to regain control.

**Comment by emacsomancer** [comment]
@Utini2000 - you can also install firejail-git from AUR instead (updating still isn't completely automatic - you can "reinstall" firejail-git to get it to repull from the git repo).

**Comment by Utini2000** [comment]
@emacsomancer thanks for updateing, my I ask if there is any difference at all between a package from aur and the same -git package from the aur ? What make the one better than the other ?

**Comment by netblue30** [comment]
@Utini2000 

Stay with the latest released version and use one of the workarounds for now. A new release is coming in the next two weeks.

**Comment by Utini2000** [comment]
@netblue30 I will, thanks for your effort ! Btw is there a way to give suggestions or contact you (e.g. irc/mail/...) ? Thanks !

For example I saw that you have "add more .profiles" in your todo list, I have a lot of them as I already created them for my system and I am trying to cover as much packages as possible. But there are other things too :P

**Comment by emacsomancer** [comment]
@Utini2000 Since what the AUR "firejail-git" package does is essential just a git pull and build, the actual script doesn't really need updating very often. But if you (re)install "firejail-git" it will re-pull from the git repo, so if the git-repo has been updated, you'll get the same thing you would have got from doing a git pull and build yourself.

@netblue30 Perhaps the issue that I'm having - that the newest git version still isn't working quite right - occurs when I open more than one instance of the browser?  I've got back to using the "echo "enable-shm = no" >> client.conf" hack for now to see if that helps.

**Comment by ilikenwf** [comment]
Slightly on topic, but people are using firejail for processes like pulse? Are you using custom bash script launchers or something to do so, since we don't really have an automated way right now beyond bash/zsh aliases, custom .desktop files, and custom launch scripts yet?

It would be nice to have as firejailed a system as possible but more advanced setups like this haven't really been documented yet to my knowledge.

**Comment by netblue30** [comment]
Sandboxing PulseAudio server should work - I didn't try it yet. 

 my system I use custom launch scripts. I place them in /usr/local/bin, so they take precedence over /bin and /usr/bin. Here is one example:
`````
$ cat  /usr/local/bin/iceweasel
#!/bin/bash
firejail --net=eth0 --iprange=192.168.1.50,192.168.1.199 --private=~/myfirefox /usr/bin/iceweasel $1
`````
I also have a GUI in the works here: https://github.com/netblue30/firetools

**Comment by ilikenwf** [comment]
I didn't consider using custom launch scripts - that's easier than using
custom .desktop files!

Very nice...very nice. Firetools is a launcher and manager, I am assuming?

Either way I added firetools to the Arch wiki, and linked it from the
security page. I'm very happy using it in conjunction with grsec.

**Comment by Utini2000** [comment]
But will custom launch scripts also "takeover" when e.g. opening iceweasel by click on a link in an email ?

**Comment by netblue30** [comment]
@Utini2000 Start Thunderbird in firejail ("firejail thunderbird") and when you click on a link the browser opens in the same sandbox as Thunderbird. Even if there is a custom launch script, firejail will detect a sandbox is already running and will not start another one.

@ilikenwf Yes, firetools is a simple launcher and manager. The problem with the custom .desktop files is they get updated by the distro.

About wine, several  people use it under firejail. The only thing not working there is seccomp -  wine is a 32bit executable, and Linux kernel doesn't support 32bit seccomp filters on a 64bit system. Same goes for Steam.

**Comment by Utini2000** [comment]
@netblue30  thank you but the "thunderbird" part was just an example :) Good to know though ! In general it would be nice to always run specific apps in firejail, no matter who/how/where they got startet. If there is a firejail profile, run in firejail ;P

**Comment by netblue30** [comment]
By default everything runs under /etc/firejail/generic.profile.If you run a program firejail recognizes, it will switch to that specific profile.

**Comment by curiosity-seeker** [comment]
> I didn't consider using custom launch scripts - that's easier than using custom .desktop files!

@netblue30 @ilikenwf : How can you use such custom launch scripts to start applications firejailed? Why is it easier than custom .desktop files? I must be missing something. Please be so kind to explain! Thanks!

**Comment by Utini2000** [comment]
@netblue30 Nope I guess I described it badly again: I mean, firejail should always run and wait in the backround and monitor which apps the system tries to start. If one of those apps has a firejail profile (or is listed in no-yet-available-firejails "auto sandbox") then firejail will interupt the system from starting this program and modifies it to start with firejail.

**Comment by netblue30** [comment]
@curiosity-seeker The idea is to build a custom launch script with the same name as your program, and store it in your path before the real program. A good place is /usrlocal/bin. The system will be tricked into running the custom launch script instead of the real program.

You can also use .desktop files. Put them on your desktop. The desktop files under /usr/share/applications/ get overwritten by your system when you update it.

**Comment by netblue30** [comment]
@Utini2000 You cannot interrupt the system, the kernel wouldn't let you. Once you tell it to start a program, it will start the program. The only thing you can do is to trick it into starting the sandbox.

**Comment by curiosity-seeker** [comment]
> The idea is to build a custom launch script with the same name as your program, and store it in your path before the real program. A good place is /usrlocal/bin. The system will be tricked into running the custom launch script instead of the real program.

>You can also use .desktop files. Put them on your desktop. The desktop files under /usr/share/applications/ get overwritten by your system when you update it. 

Yes, I have been using desktop files so far. So you are saying that those scripts under /usr/local/bin always take precedence regardless if the desktop files are located in /usr/share/applications or ~/.local/share/applications? I didn't know that.

**Comment by curiosity-seeker** [comment]
> Start Thunderbird in firejail ("firejail thunderbird") and when you click on a link the browser opens in the same sandbox as Thunderbird. Even if there is a custom launch script, firejail will detect a sandbox is already running and will not start another one.

I'm not sure that I understand. I start firejail thunderbird and click a link but firejail --tree shows, e.g. the following:

1494:xxx:/usr/bin/firejail thunderbird 
  1495:xxx:thunderbird 
2541:xxx:/usr/bin/firejail firefox http://www.heise.de/security/meldung/Kritische-Flash-Luecke-Adobe-  stellt-Patch-in-Aussicht-2847993.html/from/nl_sec_summ?wt_mc=nl.heisec-summary.2015-10-
  2542:xxx:/bin/bash /usr/local/bin/firefox http://www.heise.de/security/meldung/Kritische-Flash-Luecke-Adobe-stellt-Patch-in-Aussicht-2847993.html/from/nl_sec_summ?wt_mc=nl.heisec-summary
    2543:xxx:firejail --profile=/home/tlu/.config/firejail/firefox.profile /usr/lib/firefox/firefox http://www.heise.de/security/meldung/Kritische-Flash-Luecke-Adobe-stellt-Patch-in-Aussic
      2544:xxx:/usr/lib/firefox/firefox http://www.heise.de/security/meldung/Kritische-Flash-Luecke-Adobe-stellt-Patch-in-Aussicht-2847993.html/from/nl_sec_summ?wt_mc=nl.heisec-summary.201
        2568:xxx:/usr/lib/mozilla/kmozillahelper

This doesn't look as if firefox is in the same sandbox as thunderbird ... ?

**Comment by netblue30** [comment]
@curiosity-seeker What firejail version are you running?

Start thunderbird/icedove from a terminal and click on a link:
`````
$ icedove 
Reading profile /etc/firejail/icedove.profile
Reading profile /etc/firejail/thunderbird.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-history.inc
Parent pid 2080, child pid 2081
Child process initialized
Warning: an existing sandbox was detected. /usr/bin/iceweasel https://github.com/netblue30/firejail/issues/83  will run without any additional sandboxing features in a /bin/sh shell
`````

You'll get that warning "an existing sandbox was detected. /usr/bin/iceweasel https://github.com/netblue30/firejail/issues/83  will run without any additional sandboxing features in a /bin/sh shell". It means firejail started the browser (firefox/iceweasel) directly, without any shell. "firejail --tree" in this moment looks like this:
`````
$ firejail --tree
2080:netblue:firejail --name=mail /usr/bin/icedove 
  2081:netblue:/usr/bin/icedove 
    2138:netblue:/bin/bash /usr/local/bin/iceweasel https://github.com/netblue30/firejail/issues/83 
      2141:netblue:/usr/bin/firejail /usr/bin/iceweasel
        2142:netblue:sh -c /usr/bin/iceweasel https://github.com/netblue30/firejail/issues/83  
          2143:netblue:/usr/bin/iceweasel https://github.com/netblue30/firejail/issues/83 
            2227:netblue:/usr/lib/iceweasel/plugin-container /usr/lib/flashplugin-nonfree/libflashplayer.so -g
`````

**Comment by curiosity-seeker** [comment]
@netblue30 : I'm using 0.9.30 on Manjaro (=Arch derivative)

> Start thunderbird/icedove from a terminal and click on a link:

I did that, and this is what I get:
`````
Reading profile /home/xxx/.config/firejail/thunderbird.profile
Reading profile /home/xxx/.config/firejail/myrules.inc
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-history.inc
Warning: user namespaces not available in the current kernel.
Parent pid 1597, child pid 1598
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized

(process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
[calBackendLoader] Using libical backend at /home/xxx/.thunderbird/gvf0q58u.default/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}/components/libical-manifest

(thunderbird:1): Gtk-WARNING **: Theme directory action/24 of theme maia has no size field

enigmail.js: Registered components
ReminderFox  clh(1)  {rmFx_cmdLine: [xpconnect wrapped nsICommandLine]}
mimeVerify.jsm: module initialized
CardDAVDirectoryFactory.js: getDirectories
  aDirName: public
  aURI: carddav://sogo-demo.inverse.ca/SOGo/dav/t3000@posteo.de/Contacts/public/
  aPrefId: ldap_2.servers.public

(thunderbird:1): Gtk-WARNING **: Theme directory action/24 of theme maia has no size field

2015-10-17 12:26:16: range_map-inl.h:91: INFO: StoreRange failed, an existing range contains or extends higher than the new range: new 0x7fe11e703000+0x85fe4, existing 0x7fe11e5f5000+0x223130
2015-10-17 12:26:16: basic_code_modules.cc:70: ERROR: Module /usr/lib/libsystemd.so.0 could not be stored
2015-10-17 12:26:16: stackwalker.cc:125: INFO: Couldn't load symbols for: /usr/lib/thunderbird/libxul.so|0CBE9F5515663EED582EC007F97877620
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288260
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b2888a8
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b287fe5
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b28800f
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288068
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b2880e0
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288098
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288058
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe10a47a801
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe0d374c418
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0xaffd2b2889cf
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x8057000aaf0f21a0
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0xaf00a8
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b2880a8
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b2880b8
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b2881a0
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0xf8771c0
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x1f0ee38
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288050
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe1000f21a0
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x100000001f0ee38
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0xaf00a8
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288778
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x4e49f25693687c00
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b289098
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe1000f21a0
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288c30
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b2881a0
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe0d374c148
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b2881c0
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288b20
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b288260
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x8000ffff
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe0d9796800
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe105eb3f70
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe0d39fb500
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x3
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe10a47a928
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7ffd2b2880d8
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x8000000800000000
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe10a47a8a8
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x4e49f25693687c00
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe1000f02af
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x4e49f25693687c00
2015-10-17 12:26:16: basic_code_modules.cc:88: INFO: No module at 0x7fe1000f21c0
`````
And firejail --tree shows:
`````
1597:xxx:firejail thunderbird 
  1598:xxx:thunderbird 
1708:xxx:/usr/bin/firejail firefox https://github.com/netblue30/firejail/issues/69#issuecomment-148692976 
  1709:xxx:/bin/bash /usr/local/bin/firefox https://github.com/netblue30/firejail/issues/69#issuecomment-148692976 
    1710:xxx:firejail --profile=/home/xxx/.config/firejail/firefox.profile /usr/lib/firefox/firefox https://github.com/netblue30/firejail/issues/69#issuecomment-148692976 
      1711:xxx:/usr/lib/firefox/firefox https://github.com/netblue30/firejail/issues/69#issuecomment-148692976 
        1735:xxx:/usr/lib/mozilla/kmozillahelper
`````

Thus, it seems that the behaviour is different from your system.

**Comment by netblue30** [comment]
That's interesting! You could get something like this if you already have firefox running in another window when you click on the link in thunderbird (I have a writeup here: https://l3net.wordpress.com/projects/firejail/firejail-faq/#firefox).

There seem to be something else going on, I'll try it here on my Arch box.

**Comment by curiosity-seeker** [comment]
> That's interesting! You could get something like this if you already have firefox running in another window when you click on the link in thunderbird 

No, Firefox was definitely not running!

**Comment by netblue30** [comment]
The communication seems to go over DBus. Thunderbird sends a message, and somebody (?) starts the browser, so the browser ends up in a different sandbox.

**Comment by curiosity-seeker** [comment]
Thanks for that info! It's all right as long as Firefox is sandboxed.

**Comment by emacsomancer** [comment]
So is the "enable-shm = no" in client.conf workaround no longer needed?

The last time I tried without the workaround (10 Oct), I still had the same issues with Pulseaudio.

**Comment by netblue30** [comment]
Yes, if you are running firejail version 0.9.32 or 0.9.34-rc1 it should be fixed.

**Comment by emacsomancer** [comment]
It's still not working for me.  If I remove the "enable-shm = no" in ~/.config/pulse/client.conf, and restart Pulseaudio, I still end up with the same issue as before.

Steps: 
(1) remove ~/.config/pulse/client.conf
(2) "pulseaudio -k && pulseaudio --start"
(3) "firejail --profile=/etc/firejail/firefox.profile firefox"
(4) open pavucontrol
(5) play music with mpd
(6) open up Youtube in firefox and play something
(7) If I look at pavucontrol, I can still see two streams active
(8) But muting pulseaudio no longer works
(9) And if I close pavucontrol and reopen it, it's again stuck on "Establishing connection to PulseAudio. Please wait...." until I do step 1 again.

If I put the enable-shm=no back in place, then things work properly.

**Comment by netblue30** [comment]
In firefox.profile, if you also whitelist ~/.config/pulse, does it work?

**Comment by netblue30** [comment]
OK, I've got it on Arch. It looks like we still need "enable-shm = no" in ~/.config/pulse/client.config.  PulseAudio cannot mix various clients with and without "enable-shm = no". 

Leave ~/.config/pulse/client.config in place. I'll update the documentation and the announcements. Thank you for reporting it.

**Comment by genodeftest** [comment]
Similar issue here with firejail from master on Fedora 23. I don't have problems playing music but I am seeing warnings like these:
`shm_open() failed: File or directory not found`
For future reference: look at https://firejail.wordpress.com/support/known-problems/ to find a workaround.

**Comment by ivan** [comment]
This also affects PulseAudio 8 in Ubuntu 16.04 and the `enable-shm = no` fix worked for me.

**Comment by netblue30** [comment]
Thanks for letting me know.

**Comment by covex** [comment]
Confirming this on Fedora 23 with firejail-0.9.28-1 from default install. Starting firefox in firejail causes the pulseaudio to stop working. Pulseaudio seems to be running but plays nothing.

Any attempt to play anything results in 
$ aplay s.wav 
shm_open() failed: No such file or directory
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
aplay: main:786: audio open error: Connection refused

PS is dead for all applications until
$ pulseudio -k; start-pulseaudio-x11

**Comment by netblue30** [comment]
You need to move to 0.9.40, there were a lot of fixes for PulseAudio since 0.9.28. Also, you would need to configure pulse this way: https://firejail.wordpress.com/support/known-problems/#pulseaudio

**Comment by tanuk** [comment]
If someone is running PA 9.0, it would be nice to get a confirmation that setting

enable-memfd = yes

in /etc/pulse/daemon.conf fixes this issue too. The option was added in PA 9.0, but it's off by default. It will be enabled by default at some point, probably in PA 10.0. The option changes the shared memory functionality so that the /dev/shm/* files aren't used any more.

**Comment by netblue30** [comment]
Thanks @tanuk

**Comment by pyamsoft** [comment]
I can confirm that using PulseAudio 9.0 and enabling the `enable-memfd = yes` option in the 
`/etc/pulse/daemon.conf` allows jailed applications to use pulseaudio.

I can also confirm that I do not have `enable-shm = no` in any of the pulseaudio client configuration files.

**Comment by netblue30** [comment]
Thanks, issue closed.
