### ISSUE TITLE
Support AppImage type 2 image format

### ISSUE THREAD

**Issue by probonopd** [netblue30/firejail#861]
Please support the AppImage [type 2 image format](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-2-image-format). This is the next-generation format that is using squashfs instead of ISO9660, and enables features such as embedded GPG signatures and other new functionality.

It should be pretty straightforward to use type 2 images, loop-mount them using the kernel with `-o,offset=xxxxx`. The offset is the [length of the ELF file](https://gist.github.com/probonopd/a490ba3401b5ef7b881d5e603fa20c93) in bytes. Appended to the ELF is the squashfs image.

Tools to work with type 2 images:
https://github.com/probonopd/appimagetool

Example type 2 image:
https://bintray.com/probono/AppImages/download_file?file_path=Leafpad-0.8.18.1.glibc2.4-x86_64.AppImage

**Comment by netblue30** [comment]
Will do!

**Comment by netblue30** [comment]
Looks pretty cool, you basically cut the size of the image in half! I have the support in, it will autodetect the type and mount iso or squashfs accordingly:
`````
$ firejail --private --appimage appimage-name
`````
For now use --private or a --profile command. I'll bring in support to pick up a profile automatically based on the application name.

**Comment by probonopd** [comment]
Cool, thanks, will test asap.

**Comment by probonopd** [comment]
Isn't it dangerous that the user can launch the app directly from `/run/firejail/appimage/appimage-...`?

**Comment by probonopd** [comment]
Do we really need that many processes around?

```
24121 ?        S      0:00 firejail --private --appimage /home/me/Downloads/Code::Blocks_IDE-16.01.glibc2.14-x86_64.AppImage
24122 ?        S<     0:00 [loop6]
24125 ?        S      0:00 firejail --private --appimage /home/me/Downloads/Code::Blocks_IDE-16.01.glibc2.14-x86_64.AppImage
24127 ?        S      0:00 /bin/bash /run/firejail/appimage/appimage-24121/AppRun
24131 ?        Sl     0:01 /run/firejail/appimage/appimage-24121/usr/bin/codeblocks
```

**Comment by netblue30** [comment]
> Do we really need that many processes around

You can get rid of 24127 if you use --shell=none. I don't know what that [loop6] process is.

> Isn't it dangerous that the user can launch the app directly from /run/firejail/appimage/appimage-...?

The idea is to mount it under /run instead of /tmp because in /tmp everybody has write access, while in /run only root can write.

**Comment by probonopd** [comment]
I think by mounting to a mountpoint starting with "." we can avoid the artefact that file managers show a new disk for a fraction of a second during mounting and unmounting:

![peek 2016-10-23 16-10](https://cloud.githubusercontent.com/assets/2480569/19626883/4f0f94fa-993b-11e6-8d28-5db903f41480.gif)

**Comment by probonopd** [comment]
`firejail --noprofile --shell=none --appimage ...` results in `Error: --shell=none configured, but no program specified`

**Comment by netblue30** [comment]
> I think by mounting to a mountpoint starting with "."

Done, grab the latest from git. I'll look into --shell=none, it looks like a bug on my side.

**Comment by probonopd** [comment]
> I think by mounting to a mountpoint starting with "."

Actually my mistake, having the mountpoint start with "." does not fix this. I currently don't know how to do this properly.

**Comment by netblue30** [comment]
No problem.
